//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class apilog
    {
        public int ApiLogId { get; set; }
        public Nullable<bool> IsError { get; set; }
        public int TestId { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorMessage { get; set; }
        public string CaseId { get; set; }
        public string SampleId { get; set; }
        public Nullable<System.DateTime> SampleDateCollected { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string LaboratoryId { get; set; }
        public string TbResult { get; set; }
        public string RifResult { get; set; }
        public string Comments { get; set; }
        public System.DateTime InitiatedOn { get; set; }
        public string InitiatedBy { get; set; }
        public bool InitiatedManually { get; set; }
    
        public virtual test test { get; set; }
    }
}
