//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.people = new HashSet<person>();
            this.regions = new HashSet<region>();
            this.states = new HashSet<state>();
            this.notificationcountries = new HashSet<notificationcountry>();
            this.deployments = new HashSet<deployment>();
        }
    
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Culture { get; set; }
    
        public virtual ICollection<person> people { get; set; }
        public virtual ICollection<region> regions { get; set; }
        public virtual ICollection<state> states { get; set; }
        public virtual ICollection<notificationcountry> notificationcountries { get; set; }
        public virtual ICollection<deployment> deployments { get; set; }
    }
}
