//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployment
    {
        public deployment()
        {
            this.devices = new HashSet<device>();
            this.devicedeploymenthistories = new HashSet<devicedeploymenthistory>();
            this.notificationdeployments = new HashSet<notificationdeployment>();
            this.tests = new HashSet<test>();
        }
    
        public int DeploymentId { get; set; }
        public string HostId { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> LgaId { get; set; }
        public string City { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Zip { get; set; }
        public Nullable<float> Latitude { get; set; }
        public Nullable<float> Longitude { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string Insertedby { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string Updatedby { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> MshLaboratoryId { get; set; }
        public Nullable<int> PartnerId { get; set; }
    
        public virtual country country { get; set; }
        public virtual lga lga { get; set; }
        public virtual region region { get; set; }
        public virtual state state { get; set; }
        public virtual ICollection<device> devices { get; set; }
        public virtual ICollection<devicedeploymenthistory> devicedeploymenthistories { get; set; }
        public virtual ICollection<notificationdeployment> notificationdeployments { get; set; }
        public virtual ICollection<test> tests { get; set; }
        public virtual partner partner { get; set; }
    }
}
