//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicetype
    {
        public devicetype()
        {
            this.devices = new HashSet<device>();
            this.testtypes = new HashSet<testtype>();
        }
    
        public int DeviceTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<device> devices { get; set; }
        public virtual ICollection<testtype> testtypes { get; set; }
    }
}
