//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public device()
        {
            this.devicedeploymenthistories = new HashSet<devicedeploymenthistory>();
        }
    
        public int DeviceId { get; set; }
        public string Serial { get; set; }
        public int CurrentDeploymentId { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string InsertedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<devicedeploymenthistory> devicedeploymenthistories { get; set; }
        public virtual deployment deployment { get; set; }
    }
}
