//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicedeploymenthistory
    {
        public int DeviceDeploymentHistoryId { get; set; }
        public int DeviceId { get; set; }
        public int DeploymentId { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string InsertedBy { get; set; }
    
        public virtual device device { get; set; }
        public virtual deployment deployment { get; set; }
    }
}
