//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class lga
    {
        public lga()
        {
            this.people = new HashSet<person>();
            this.notificationlgas = new HashSet<notificationlga>();
            this.deployments = new HashSet<deployment>();
        }
    
        public int LgaId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<person> people { get; set; }
        public virtual state state { get; set; }
        public virtual ICollection<notificationlga> notificationlgas { get; set; }
        public virtual ICollection<deployment> deployments { get; set; }
    }
}
