//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificationregion
    {
        public int NotificationRegionId { get; set; }
        public int NotificationId { get; set; }
        public int RegionId { get; set; }
    
        public virtual region region { get; set; }
        public virtual notification notification { get; set; }
    }
}
