//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificationperson
    {
        public int NotificationPersonId { get; set; }
        public int NotificationId { get; set; }
        public int PersonId { get; set; }
        public bool Sms { get; set; }
        public bool Email { get; set; }
        public bool Phone { get; set; }
    
        public virtual person person { get; set; }
        public virtual notification notification { get; set; }
    }
}
