//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificationlog
    {
        public int NotificationLogId { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public string NotificationName { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string PersonName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool Sms { get; set; }
        public bool Email { get; set; }
        public bool Phone { get; set; }
        public System.DateTime SentOn { get; set; }
        public string SentBy { get; set; }
    
        public virtual notification notification { get; set; }
        public virtual person person { get; set; }
    }
}
