//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner
    {
        public partner()
        {
            this.deployments = new HashSet<deployment>();
        }
    
        public int PartnerId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<deployment> deployments { get; set; }
    }
}
