//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.notificationpersons = new HashSet<notificationperson>();
            this.notificationlogs = new HashSet<notificationlog>();
        }
    
        public int PersonId { get; set; }
        public string Email { get; set; }
        public string Cell { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> LgaId { get; set; }
        public string Phone { get; set; }
        public string Title { get; set; }
        public string EmailAlt { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
    
        public virtual country country { get; set; }
        public virtual lga lga { get; set; }
        public virtual region region { get; set; }
        public virtual state state { get; set; }
        public virtual ICollection<notificationperson> notificationpersons { get; set; }
        public virtual ICollection<notificationlog> notificationlogs { get; set; }
    }
}
