//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class rawmessage
    {
        public int RawMessageId { get; set; }
        public Nullable<int> TestId { get; set; }
        public string Message { get; set; }
    
        public virtual test test { get; set; }
    }
}
