//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class resulttestcode
    {
        public resulttestcode()
        {
            this.testresults = new HashSet<testresult>();
            this.notificationresults = new HashSet<notificationresult>();
        }
    
        public int ResultTestCodeId { get; set; }
        public string ResultTestCode1 { get; set; }
        public string Description { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string InsertedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<testresult> testresults { get; set; }
        public virtual ICollection<notificationresult> notificationresults { get; set; }
    }
}
