//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.lgas = new HashSet<lga>();
            this.people = new HashSet<person>();
            this.notificationstates = new HashSet<notificationstate>();
            this.deployments = new HashSet<deployment>();
        }
    
        public int StateId { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual country country { get; set; }
        public virtual ICollection<lga> lgas { get; set; }
        public virtual ICollection<person> people { get; set; }
        public virtual ICollection<notificationstate> notificationstates { get; set; }
        public virtual ICollection<deployment> deployments { get; set; }
    }
}
