//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GxAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class testtype
    {
        public testtype()
        {
            this.tests = new HashSet<test>();
        }
    
        public int TestTypeId { get; set; }
        public int DeviceTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual devicetype devicetype { get; set; }
        public virtual ICollection<test> tests { get; set; }
    }
}
